image: $REPO_URL/stage

services:
  - docker:dind

stages:
  - build
  - test
  - e2e
  - release

variables:
  DOCKER_HOST: tcp://localhost:2375/

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################

build-linux:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - kube
  script:
    - docker pull $REPO_URL/contractor:latest || true
    - docker build -t $REPO_URL/contractor:$CI_COMMIT_SHA -f docker/Dockerfile --cache-from=$REPO_URL/contractor:latest .
    - docker push $REPO_URL/contractor:$CI_COMMIT_SHA


###############################################################
# Test Stage
###############################################################

test-linux:
  image: python:3.6
  tags:
    - kube
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt-get update && apt-get install -y libudev-dev libusb-1.0-0-dev
    - pip install tox
  script:
    - tox -e py36

###############################################################
# End-to-end Stage
###############################################################

kick-e2e:
    tags:
      - kube
    stage: e2e
    script:
    - set -e

    # kick e2e
    - >-
      E2E_PIPELINE_ID=`curl
      --silent
      --request POST
      --form "token=$CI_JOB_TOKEN"
      --form "variables[SOURCE_PROJECT]=$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
      --form "variables[SOURCE_BRANCH]=$CI_COMMIT_REF_NAME"
      --form ref=master
      "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/trigger/pipeline" | jq -r ".id"`

    # poll for it to finish
    - >-
      while [ -z $PIPELINE_STATUS ] || [ $PIPELINE_STATUS = "pending" ] || [ $PIPELINE_STATUS = "running" ]; do
        PIPELINE_STATUS=`curl \
          --silent \
          --header "PRIVATE-TOKEN: $CI_CUSTOM_CI_PAT" \
          "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/pipelines/$E2E_PIPELINE_ID" | jq -r ".status"`
        echo "waiting for e2e pipeline ...";
        sleep 5;
      done

    # check for success
    - >-
      if [ $PIPELINE_STATUS != "success" ]; then
        echo "failure further down the pipeline"
        exit 1
      fi

###############################################################
# Release Stage
###############################################################

release-latest-linux:
  stage: release
  tags:
    - kube
  only:
    - master
  script:
    # Gets the current image that was built in the CI for this commit
    - docker pull $REPO_URL/contractor:$CI_COMMIT_SHA
    # Creates new tags for this image, one that should go to AWS and another to DockerHub with the tag "latest"
    - docker tag $REPO_URL/contractor:$CI_COMMIT_SHA $REPO_URL/contractor:latest
    - docker tag $REPO_URL/contractor:$CI_COMMIT_SHA polyswarm/contractor:latest
    # Pushes to AWS
    - docker push $REPO_URL/contractor:latest
    # Pushes to Docker Hub
    - docker logout
    - docker login -u "$CI_CUSTOM_DOCKER_HUB_USERNAME" -p "$CI_CUSTOM_DOCKER_HUB_PASSWORD"
    - docker push polyswarm/contractor:latest
