image: $REPO_URL/stage

services:
  - docker:dind

stages:
  - build
  - test
  - e2e
  - release

variables:
  DOCKER_HOST: tcp://localhost:2375/

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################

build-linux:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - kube
  script:
    - docker pull $REPO_URL/contractor:latest || true
    - docker build -t $REPO_URL/contractor:${MANUAL_IMAGE_TAG:-$CI_COMMIT_SHA} -f docker/Dockerfile --cache-from=$REPO_URL/contractor:latest .
    - docker push $REPO_URL/contractor:${MANUAL_IMAGE_TAG:-$CI_COMMIT_SHA}


###############################################################
# Test Stage
###############################################################

test-linux:
  image: python:3.6
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt-get update && apt-get install -y libudev-dev libusb-1.0-0-dev
    - pip install tox
  script:
    - tox -e py36

###############################################################
# End-to-end Stage
###############################################################

# triggers itself in a new pipeline with the MANUAL_IMAGE_TAG=manual-tag
e2e-self-trigger-with-manual-tag:
  stage: e2e
  tags:
    - kube
  script:
    - >-
      curl
      --request POST
      --form "token=$CI_JOB_TOKEN"
      --form "variables[MANUAL_IMAGE_TAG]=manual-tag"
      --form ref=master
      "https://gitlab.polyswarm.io/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  when: manual


###############################################################
# Release Stage
###############################################################

release-latest-linux:
  stage: release
  tags:
    - kube
  only:
    refs:
      - master
    variables:
      - $RELEASE_LATEST == "true"
  script:
    # Gets the current image that was built in the CI for this commit
    - docker pull $REPO_URL/contractor:${MANUAL_IMAGE_TAG:-$CI_COMMIT_SHA}
    # Creates new tags for this image, one that should go to AWS and another to DockerHub with the tag "latest"
    - docker tag $REPO_URL/contractor:${MANUAL_IMAGE_TAG:-$CI_COMMIT_SHA} $REPO_URL/contractor:latest
    - docker tag $REPO_URL/contractor:${MANUAL_IMAGE_TAG:-$CI_COMMIT_SHA} polyswarm/contractor:latest
    # Pushes to AWS
    - docker push $REPO_URL/contractor:latest
    # Pushes to Docker Hub
    - docker logout
    - docker login -u "$CI_CUSTOM_DOCKER_HUB_USERNAME" -p "$CI_CUSTOM_DOCKER_HUB_PASSWORD"
    - docker push polyswarm/contractor:latest
